# Site settings
title: Azaé
baseline: Catalyseur d'agilité

url: "http://azae.net"
baseurl: ""

contact:
  email: contact@azae.net
  phone: +33 3 66 72 80 22
  address: "139 Rue des Arts, 59100 Roubaix"

social:
- link: https://github.com/azae
  icon: fa-github
- link: https://google.com/+AzaeNet
  icon: fa-google
- link: http://twitter.com/azae_net
  icon: fa-twitter
- link: http://www.linkedin.com/company/aza-
  icon: fa-linkedin
- link: http://www.viadeo.com/fr/company/azae
  icon: socicon-viadeo


markdown: kramdown


gems:
- jekyll-paginate


defaults:
- scope:
    path: "articles"
    type: "posts"
  values:
    permalink: /articles/:title
    layout: post


exclude:
- README.md
- Dockerfile
- Gemfile